#
# Makefile for industrial I/O potentiometer drivers
#

# When adding new entries keep the list in alphabetical order
obj-$(CONFIG_DS1803) += ds1803.o
obj-$(CONFIG_MAX5487) += max5487.o
obj-$(CONFIG_MCP4131) += mcp4131.o
obj-$(CONFIG_MCP4531) += mcp4531.o
obj-$(CONFIG_TPL0102) += tpl0102.o

#100ask expansion board ds18b20 module driver
obj-$(CONFIG_DS18B20_MOD) += 100ask_ds18b20.o
