#
# Makefile for IIO humidity sensor drivers
#

obj-$(CONFIG_AM2315) += am2315.o
obj-$(CONFIG_DHT11) += dht11.o
obj-$(CONFIG_HDC100X) += hdc100x.o
obj-$(CONFIG_HTU21) += htu21.o
obj-$(CONFIG_SI7005) += si7005.o
obj-$(CONFIG_SI7020) += si7020.o


#100ask expansion board dht11 module driver
obj-$(CONFIG_DHT11_MOD) +=  100ask_dht11.o
